baseURL = "http://example.org/"
languageCode = "en-uk"
#theme = "contrast"
theme = "hello-friend-ng"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Metadata mostly used in document's head
  description = "devops tech-notes by Alan Platt"
  keywords = "homepage, devops, operations, development, programming"
  images = [""]

  # Directory name of your blog content (default is `content/posts`)
  contentTypeName = "posts"

  # Default theme "light" or "dark"
  defaultTheme = "dark"

[languages]
  [languages.en]
    title = "tech-notes"
    subtitle = ""
    keywords = ""
    copyright = ""
    readOtherPosts = ""

    [languages.en.params.logo]
      logoText = "tech-notes"
      logoHomeLink = "/posts"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
  [[menu.main]]
    identifier = "posts"
    name       = "posts"
    url        = "/posts"
